-- SQL script to create the document_chunks table and related components
-- Run this in your Supabase SQL editor if the document_chunks table is missing

-- Enable necessary extensions (if not already enabled)
CREATE EXTENSION IF NOT EXISTS "vector";

-- Create document_chunks table if it doesn't exist
CREATE TABLE IF NOT EXISTS document_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    embedding VECTOR(1536),
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_document_chunks_document_id ON document_chunks(document_id);
CREATE INDEX IF NOT EXISTS idx_document_chunks_embedding ON document_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- Enable Row Level Security
ALTER TABLE document_chunks ENABLE ROW LEVEL SECURITY;

-- Create policy for authenticated users (adjust according to your authentication setup)
CREATE POLICY "Allow full access to authenticated users" ON document_chunks FOR ALL TO authenticated USING (true);

-- Verify the table was created
SELECT 'document_chunks table created successfully!' as status;
