# Frontend Cloud Build Configuration
steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Update npm to latest version
        npm install -g npm@latest
        
        # Install dependencies
        npm install
    dir: '.'
    id: 'install-dependencies'

  # Build the React app
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create .env file with environment variables
        echo "VITE_API_URL=${_API_URL}" > .env
        echo "VITE_SUPABASE_URL=${_SUPABASE_URL}" >> .env
        echo "VITE_SUPABASE_ANON_KEY=${_SUPABASE_KEY}" >> .env
        
        # Build the app
        npm run build
    env:
      - 'VITE_API_URL=${_API_URL}'
      - 'VITE_SUPABASE_URL=${_SUPABASE_URL}'
      - 'VITE_SUPABASE_ANON_KEY=${_SUPABASE_KEY}'
    dir: '.'
    id: 'build-frontend'
    waitFor: ['install-dependencies']

  # Deploy to Google App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Exclude backend directories from deployment
        echo "python-backend/" >> .gcloudignore
        echo "workflow-ai-backend/" >> .gcloudignore
        
        # Deploy to App Engine
        gcloud app deploy app.yaml \
          --version=$COMMIT_SHA \
          --quiet
    dir: '.'
    id: 'deploy-frontend'
    waitFor: ['build-frontend']

# Substitution variables to be set in the Cloud Build trigger
substitutions:
  _API_URL: 'https://fabledash-backend-xxxxxxxx-uc.a.run.app'
  _SUPABASE_URL: 'https://your-supabase-project.supabase.co'
  _SUPABASE_KEY: 'your-supabase-anon-key'

# Timeout for the build
timeout: '1800s'

# Only trigger builds on the main branch
options:
  logging: CLOUD_LOGGING_ONLY
